import Post from '@/components/Posts/Post/Post';
import Layout from '../components/Layouts/Layout';

export default function PostsPage() {
  return (
    <>
      <Layout>
        <div className='text-4xl text-center my-16 flex-1 items-center justify-center'>
          <Post title='Title'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga possimus repellat corrupti! Tenetur commodi omnis recusandae ipsam voluptates unde? Harum pariatur soluta expedita atque commodi dolorum. Ullam alias deleniti possimus magnam laborum non qui est architecto sit, animi dolores consequuntur, aspernatur, omnis sint assumenda obcaecati molestiae nobis error distinctio quia cumque dicta ducimus vel excepturi. At, placeat? Maiores doloremque provident quod illo, ducimus aut! Numquam eos accusantium enim quam, sequi consectetur neque molestiae dolorum vitae aut eveniet nemo ullam soluta ea quis maxime labore alias? Ut maiores totam quaerat voluptatum veritatis nemo similique accusamus libero voluptates, beatae atque, ratione cum rerum, et exercitationem deleniti? Architecto reiciendis labore corporis corrupti enim dolorem distinctio perspiciatis vero. At, placeat? Maiores doloremque provident quod illo, ducimus aut! Numquam eos accusantium enim quam, sequi consectetur neque molestiae dolorum vitae aut eveniet nemo ullam soluta ea quis maxime labore alias? Ut maiores totam quaerat voluptatum veritatis nemo similique accusamus libero voluptates, beatae atque, ratione cum rerum, et exercitationem deleniti? Architecto reiciendis labore corporis corrupti enim dolorem distinctio perspiciatis vero.</Post>
          <Post title='Title'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga possimus repellat corrupti! Tenetur commodi omnis recusandae ipsam voluptates unde? Harum pariatur soluta expedita atque commodi dolorum. Ullam alias deleniti possimus magnam laborum non qui est architecto sit, animi dolores consequuntur, aspernatur, omnis sint assumenda obcaecati molestiae nobis error distinctio quia cumque dicta ducimus vel excepturi. At, placeat? Maiores doloremque provident quod illo, ducimus aut! Numquam eos accusantium enim quam, sequi consectetur neque molestiae dolorum vitae aut eveniet nemo ullam soluta ea quis maxime labore alias? Ut maiores totam quaerat voluptatum veritatis nemo similique accusamus libero voluptates, beatae atque, ratione cum rerum, et exercitationem deleniti? Architecto reiciendis labore corporis corrupti enim dolorem distinctio perspiciatis vero. At, placeat? Maiores doloremque provident quod illo, ducimus aut! Numquam eos accusantium enim quam, sequi consectetur neque molestiae dolorum vitae aut eveniet nemo ullam soluta ea quis maxime labore alias? Ut maiores totam quaerat voluptatum veritatis nemo similique accusamus libero voluptates, beatae atque, ratione cum rerum, et exercitationem deleniti? Architecto reiciendis labore corporis corrupti enim dolorem distinctio perspiciatis vero.</Post>
        </div>
      </Layout>
    </>
  );
}
